### ISSUE TITLE
[discussion] Did you consider any strategy for subclassing components?

### ISSUE THREAD

**Issue by jnak** [opudalo/wap-css-example#1]
A friend and I were about to do the same as you just did. So thanks for putting that up :)

One case we wanted to support that you don't seem to be doing now is supporting subclassing of components. Say you want a black button and a green button and reuse most of the same code. 

Did you think of that case ?

Thanks!
J

**Comment by opudalo** [comment]
Something like this? 

```css
.common { 
  // common styles
}
.black {
  // styles to overwrite
}
```
```javascript
<div className={cn(button.common, button.black)}>
```
or 
```css
.common, .black { 
  // shared styles goes here
}
.black {
  // variation
}
```
```javascript
<div className={button.black}>
```
